# Generated by Django 6.1 on 2026-09-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikeviewcount',
            old_name='like_count',
            new_name='likes_count',
        ),
        migrations.RenameField(
            model_name='postlikeviewcount',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
