# Generated by Django 6.1 on 2026-09-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_content_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically the first time status becomes PUBLISHED', null=True),
        ),
        migrations.AlterModelTable(
            name='postlikeviewcount',
            table='Post_Metrics',
        ),
    ]
