# Generated by Django 6.1 on 2026-09-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_published_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlikeviewcount',
            options={'verbose_name': 'Post_Metric', 'verbose_name_plural': 'Post_Metrics'},
        ),
    ]
