# Generated by Django 6.1 on 2026-08-24 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='account/avatar/')),
                ('resume', models.FileField(upload_to='account/document/')),
                ('github_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('x_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('website_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('years_of_experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('is_available_for_hire', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
