# Generated by Django 6.1 on 2026-08-24 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='account/avatar/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='account/document/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='x_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
