# Generated by Django 6.1 on 2026-08-24 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('timestampmixins_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.timestampmixins')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            bases=('shared.timestampmixins',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('timestampmixins_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.timestampmixins')),
                ('instituition', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=30)),
                ('field_of_study', models.CharField(max_length=30)),
                ('start_year', models.DateTimeField()),
                ('end_year', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, null=True)),
            ],
            bases=('shared.timestampmixins',),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('timestampmixins_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.timestampmixins')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('Ft', 'Full Time'), ('Pt', 'Part Time'), ('Ir', 'Internship'), ('Fl', 'Freelance'), ('Cr', 'Contract')], max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('company_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date'],
            },
            bases=('shared.timestampmixins',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('timestampmixins_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.timestampmixins')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Fe', 'Frontend'), ('Be', 'Backend'), ('Db', 'Database'), ('Do', 'DevOps'), ('To', 'Tools'), ('Ss', 'Soft Skill')], max_length=2)),
                ('proficiency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('icon', models.ImageField(upload_to='portfolio/icon/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            bases=('shared.timestampmixins',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('timestampmixins_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.timestampmixins')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='portfolio/project/coverImage/')),
                ('category', models.CharField(choices=[('We', 'Web'), ('Mo', 'Mobile'), ('Ap', 'API'), ('Ml', 'ML'), ('Ot', 'Other')], max_length=2)),
                ('live_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('github_url', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('is_featured', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('skill', models.ManyToManyField(related_name='skills', to='portfolio.skill')),
            ],
            bases=('shared.timestampmixins',),
        ),
    ]
