# Generated by Django 6.1 on 2026-08-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='portfolio/skill/icon/'),
        ),
    ]
