# Generated by Django 6.1 on 2026-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API'), ('ml', 'ML'), ('other', 'Other')], max_length=6),
        ),
    ]
