# Generated by Django 6.1 on 2026-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
